name: Development Deployment

on:
  push:
    branches:
      - dev

jobs:
  static-checks:
    uses: ./.github/workflows/static-checks.yml

  deploy:
    needs: static-checks
    uses: ./.github/workflows/deploy.yml
    with:
      environment: development
      branch: dev
    secrets: inherit
